2018.05.11
akbooer/openLuup pull request #8
Opened 2018-05-12 14:29 UTC by rafale77

After more testing, I think this is ready. I also realized it is likely easier to review changes Vs. your development branch this is based on.

2018-05-15 10:06 UTC, akbooer requested changes
I like the RunScene idea.  Your intention is to expose the otherwise hidden device #0 RunScene action so that is may be selected as part of another scene action.  This is what was previously done for the SetHouseMode action.

Vera/MiOS suffers desperately from inconsistent naming, so my approach would be to retain the original  action name "RunScene" and parameter name "SceneNum".

2018-05-15 13:46 UTC, rafale77 reviewed
Agree!

2018-05-15 13:54 UTC, rafale77 commented
Still learning about github... apparently approving the change pushed it directly into my repo so it should be all good. If you merge my development into yours, you will get all the changes into your development branch including your suggested change.

2018-05-15 17:36 UTC, akbooer commented on openLuup/init.lua
> -  VERSION       = "2018.04.29",
Actually, nothing in the init module should be changed.

The changes made here have no effect, and, anyway, the parameter list of the luup.create_device() request should not be changed.

2018-05-15 17:40 UTC, akbooer commented on openLuup/scenes.lua
> +  VERSION       = "2018.05.11",
You've identified the root cause of this issue, but the solution is not complete.  

In particular, the same problem would arise if the global scene prolog routine (not a feature of Vera) rejected the scene run request.  I also need to consider what to do for 'paused' scenes.

The variable 't' can, conceptually, be a timer OR a trigger, and they should not have run times added.

So I will fix this, but not in this manner.

2018-05-15 19:23 UTC, rafale77 commented on openLuup/init.lua
> -  VERSION       = "2018.04.29",
I realized this after it was done. Then I thought that these attributes are on all devices so why not initiate them? It doesn’t hurt.

2018-05-15 19:25 UTC, rafale77 commented on openLuup/scenes.lua
> +  VERSION       = "2018.05.11",
Ok. I wondered about the global stop as well. I preferred not to touch it since I did not know where they would be blocked. As for the paused ones, I tested this. Pausing or unpausing the scene actually updates the next run so it is not a problem

2018-05-15 19:25 UTC, akbooer commented on openLuup/virtualfilesystem.lua
> +      </argumentList>
This </argument> list tag should not be here.

2018-06-17 18:59 UTC, akbooer commented
Most proposed functionality included in future commits, but implemented  differently.

Thanks for your suggestions.

2018-06-17 18:59 UTC, closed without merging